[package]
authors = ["Florent Nuttens"]
name = "nu_plugin_hmac"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
hmac = "0.12.1"
nu-plugin = "0.93.0"
nu-protocol = "0.93.0"
sha2 = "0.10.8"
